### ISSUE TITLE
Possibly broken, unable to access blocks

### ISSUE THREAD

**Issue by matt3224** [pristas-peter/wp-graphql-gutenberg-acf#12]
Hi Peter,

I tried your wp-graphql-gutenberg plugin which works ok but this one doesnt.

I have tried it by itself and with the wp-graphql-gutenberg but no joy, i presume it doesnt need that as a dependancy.

I might be doing something wrong somewhere, happy to give you any info that may be useful

Thanks!

**Comment by ibjorn** [comment]
It seems I have the same issue. Last night I upgraded wp-graphql, wp-graphiql, wp-graphql-gutenberg and wp-graphql-gutenberg-acf. 

I run into this error:

`Call to undefined method WPGraphQLGutenberg\\WPGraphQLGutenberg::format_graphql_block_type_name()`

After systematically disabling and enabling plugins I narrowed it down to be wp-graphql-gutenberg-acf.

In GraphiQL I get this:

`{
  "code": "internal_server_error",
  "message": "<p>There has been a critical error on your website.</p><p><a href=\"https://wordpress.org/support/article/debugging-in-wordpress/\">Learn more about debugging in WordPress.</a></p>",
  "data": {
    "status": 500
  },
  "additional_errors": []
}`

WordPress 5.4.1
PHP 7.3.17

**Comment by matt3224** [comment]
Ah yes this looks very familiar,

**Comment by pristas-peter** [comment]
Sorry guys i have not updated the plugin yet, will do soon.

**Comment by pristas-peter** [comment]
Fixed in cf6c3629153855372c85c4d24d0f8c6f73ec9691

Released in v0.2.0
